const shopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  FETCH_SINGLE_TOUR_START: "FETCH_SINGLE_TOUR_START",
  FETCH_SINGLE_TOUR_SUCCESS: "FETCH_SINGLE_TOUR_SUCCESS",
  FETCH_SINGLE_TOUR_FAILURE: "FETCH_SINGLE_TOUR_FAILURE",
  FETCH_REVIEWS_START: "FETCH_REVIEWS_START",
  FETCH_REVIEWS_SUCCESS: "FETCH_REVIEWS_SUCCESS",
  FETCH_REVIEWS_FAILURE: "FETCH_REVIEWS_FAILURE",
  FETCH_TOUR_STATS_START: "FETCH_TOUR_STATS_START",
  FETCH_TOUR_STATS_SUCCESS: "FETCH_TOUR_STATS_SUCCESS",
  FETCH_TOUR_STATS_FAILURE: "FETCH_TOUR_STATS_FAILURE"
}

export default shopActionTypes


/*
flux-standard-action

{
  type: 'ADD_TODO',
  payload: {
    text: 'Do something.'
  }
}

*/
